travis:
  secure:
    BINSTAR_TOKEN: kx8HxA0AsX4yuNDjyUgUdxuZY+tddUqIEdqhWPEIWG6bjmw2/1HdFCuy8EPPGPxyn3MgrMLVrpnJEyoLLSYmanEY9tjOG2t/IhlOn/KnY1PgacqxNGclqwNuVCyAedlCLOk89E0PYx1m47lqo8QGV/D7qO+mv5BN+3k3JieowRwgDO3cjpoV981OQGMjGQGcCxTu6sgB8P17mukpWvE8UrV/p4/4LnUqsmjswg+3TVAUrRw5y6Xw0llNl4HFr3ozQx3/zKCQWs6yLQ5o6ieIdDrrLiQv9sCLidB/2JC4HiZhiFb95+E1UyLwnzn4NjB9twYTNIJABlXp/L5BvandYHnVVcr04XrUjh22YjGaH/J71VDO7xPbsdtFNGNjRkF0GC4/hXge5ydxOlaTb22HvsxjF/WBj+4Kkxy1JkJkzvtzSbjR4tzucHen+lzbZiJC2cuWFjpNV3UMn+1jHOyLZANtslaPjJwJ5KHgLCMk7MUnoVfLcDnIN5OhkC5IxyTvZuNwN/lxpVlcVnHSdNIp1Iw7y6ILjRDhT9LLXOiNkNmYuIjhGe5Z6JP/FKA8IpRb5J2mZv9zvjkT0muYb0kSKJorGIl2GAeK7YWvBeS7ZbBBoW8e81g6H77a9dy8/nhqFSdMK7ocqXch1sNgXVzn79g0GtMfAzrUEXige3dRq8M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
